services:
  backend:
    build:
      context: ./apps/slideconvert-backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - R2_ACCESS_KEY=${R2_ACCESS_KEY}
      - R2_SECRET_KEY=${R2_SECRET_KEY}
      - R2_ENDPOINT_URL=${R2_ENDPOINT_URL}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
    depends_on:
      - redis
      - unoserver
    volumes:
      - ./apps/slideconvert-backend:/app
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-slideconvert123} --appendonly yes --appendfsync everysec
    volumes:
      - redis-data:/data
  unoserver:
    image: libreofficedocker/libreoffice-unoserver:3.19-9c28c22
    ports:
      - "2003:2003" # unoserver api port
volumes:
  redis-data:
