services:
  backend:
    build:
      context: .
      dockerfile: ./apps/slideconvert-backend/Dockerfile
    ports:
      - "8000:80"
    env_file:
      - ./apps/slideconvert-backend/.env
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}
    depends_on:
      - redis
      - unoserver
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-slideconvert123} --appendonly yes --appendfsync everysec
    volumes:
      - redis-data:/data
  unoserver:
    image: libreofficedocker/libreoffice-unoserver:3.19-9c28c22
    ports:
      - "2004:2004"
volumes:
  redis-data:
