FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
COPY ./apps/slideconvert-backend/ /app
WORKDIR /app
RUN uv sync --frozen --no-cache

ENV REDIS_URL=${REDIS_URL}

CMD /bin/sh -c "echo 'REDIS_URL is: $REDIS_URL' && /app/.venv/bin/rq worker --url '$REDIS_URL'"